# Generated by Django 4.1.7 on 2024-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('inject_type', models.CharField(max_length=100, null=True)),
                ('fault_type', models.CharField(max_length=255, null=True)),
                ('spec', models.CharField(max_length=10000, null=True)),
                ('schedule', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
