# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.20.1-alpine@sha256:18da4399cedd9e383beb6b104d43aa1d48bd41167e312bb5306d72c51bd11548 as builder
RUN apk add --no-cache ca-certificates git
RUN apk add build-base
WORKDIR /src

# restore dependencies
COPY go.mod go.sum ./
ENV GOPROXY=https://proxy.golang.com.cn,direct
RUN go mod download

RUN go get github.com/apache/skywalking-go

COPY . .
# RUN go build -toolexec="/src/skywalking-go/tools/go-agent" -a -o /checkoutservice .

From apache/skywalking-go-agent:0.2.0-go

COPY --from=builder /checkoutservice /src/checkoutservice

RUN skywalking-go-agent -inject /src/checkoutservice

RUN go build -toolexec="skywalking-go-agent" -a /src/checkoutservice
