{
 "title": "AIOps Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "线程数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_threads{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_threads{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_threads{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_threads{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_threads{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_threads{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_threads{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_threads{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_threads{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_threads{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "5 分钟内平均内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_memory_usage_bytes{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"checkoutservice.+\"}[$__rate_interval])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_memory_usage_bytes{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "允许的最大线程数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "container_threads_max{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_threads_max{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_threads_max{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_threads_max{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_threads_max{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_threads_max{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_threads_max{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_threads_max{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_threads_max{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_threads_max{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "5 分钟内平均被限制的 CPU 周期",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"checkoutservice.+\"}[5m])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    }
   ]
  },
  {
   "title": "工作状态",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(container_tasks_state{pod=~\"frontend.+\"})",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(container_tasks_state{pod=~\"paymentservice.+\"})",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "sum(container_tasks_state{pod=~\"recommendationservice.+\"})",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "sum(container_tasks_state{pod=~\"checkoutservice.+\"})",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "sum(container_tasks_state{pod=~\"emailservice.+\"})",
     "legendFormat": "emailservice"
    },
    {
     "expr": "sum(container_tasks_state{pod=~\"cartservice.+\"})",
     "legendFormat": "cartservice"
    },
    {
     "expr": "sum(container_tasks_state{pod=~\"currencyservice.+\"})",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "sum(container_tasks_state{pod=~\"productcatalogservice.+\"})",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "sum(container_tasks_state{pod=~\"redis.+\"})",
     "legendFormat": "redis"
    },
    {
     "expr": "sum(container_tasks_state{pod=~\"shippingservice.+\"})",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": " 5 分钟内平均 CPU CFS 周期数量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_periods_total{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_cpu_cfs_periods_total{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_cpu_cfs_periods_total{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_cpu_cfs_periods_total{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_cpu_cfs_periods_total{pod=~\"checkoutservice.+\"}[5m])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_cpu_cfs_periods_total{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_cpu_cfs_periods_total{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_cpu_cfs_periods_total{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_cpu_cfs_periods_total{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    },
    {
     "expr": "rate(container_cpu_cfs_periods_total{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    }
   ]
  },
  {
   "title": "开始时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "container_start_time_seconds{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_start_time_seconds{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_start_time_seconds{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_start_time_seconds{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_start_time_seconds{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_start_time_seconds{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_start_time_seconds{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_start_time_seconds{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_start_time_seconds{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_start_time_seconds{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": " 5 分钟内平均消耗的系统 CPU 时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{pod=~\"checkoutservice.+\"}[5m])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    }
   ]
  },
  {
   "title": "虚拟内存限制",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "container_spec_memory_swap_limit_bytes{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_spec_memory_swap_limit_bytes{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_spec_memory_swap_limit_bytes{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_spec_memory_swap_limit_bytes{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_spec_memory_swap_limit_bytes{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_spec_memory_swap_limit_bytes{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_spec_memory_swap_limit_bytes{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_spec_memory_swap_limit_bytes{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_spec_memory_swap_limit_bytes{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_spec_memory_swap_limit_bytes{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "5 分钟内平均被限制的 CPU 时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"checkoutservice.+\"}[5m])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    }
   ]
  },
  {
   "title": "物理内存限制",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "container_spec_memory_reservation_limit_bytes{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_spec_memory_reservation_limit_bytes{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_spec_memory_reservation_limit_bytes{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_spec_memory_reservation_limit_bytes{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_spec_memory_reservation_limit_bytes{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_spec_memory_reservation_limit_bytes{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_spec_memory_reservation_limit_bytes{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_spec_memory_reservation_limit_bytes{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_spec_memory_reservation_limit_bytes{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_spec_memory_reservation_limit_bytes{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "5 分钟内平均 CPU 使用时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"checkoutservice.+\"}[5m])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    }
   ]
  },
  {
   "title": "内存使用量限制",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": " CPU 资源分享值",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "container_spec_cpu_shares{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_spec_cpu_shares{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_spec_cpu_shares{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_spec_cpu_shares{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_spec_cpu_shares{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_spec_cpu_shares{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_spec_cpu_shares{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_spec_cpu_shares{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_spec_cpu_shares{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_spec_cpu_shares{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "使用 CPU 时间周期总量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_spec_cpu_quota{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_spec_cpu_quota{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_spec_cpu_quota{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_spec_cpu_quota{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_spec_cpu_quota{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_spec_cpu_quota{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_spec_cpu_quota{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_spec_cpu_quota{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_spec_cpu_quota{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": " CPU 时间周期",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "container_spec_cpu_period{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_spec_cpu_period{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_spec_cpu_period{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_spec_cpu_period{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_spec_cpu_period{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_spec_cpu_period{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_spec_cpu_period{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_spec_cpu_period{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_spec_cpu_period{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_spec_cpu_period{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "打开的套接字数量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "container_sockets{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_sockets{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_sockets{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_sockets{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_sockets{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_sockets{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_sockets{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_sockets{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_sockets{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_sockets{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "运行的进程数量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "container_processes{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_processes{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_processes{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_processes{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_processes{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_processes{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_processes{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_processes{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_processes{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_processes{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": " 5 分钟内平均 OOM（Out of Memory）事件数量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "rate(container_oom_events_total{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_oom_events_total{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_oom_events_total{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_oom_events_total{pod=~\"checkoutservice.+\"}[$__rate_interval])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_oom_events_total{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_oom_events_total{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_oom_events_total{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_oom_events_total{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_oom_events_total{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    },
    {
     "expr": "rate(container_oom_events_total{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "5 分钟内平均工作集大小",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "rate(container_memory_working_set_bytes{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_memory_working_set_bytes{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_memory_working_set_bytes{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_memory_working_set_bytes{pod=~\"checkoutservice.+\"}[$__rate_interval])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_memory_working_set_bytes{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_memory_working_set_bytes{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_memory_working_set_bytes{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_memory_working_set_bytes{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_memory_working_set_bytes{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    },
    {
     "expr": "rate(container_memory_working_set_bytes{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "虚拟内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "container_memory_swap{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_memory_swap{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_memory_swap{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_memory_swap{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_memory_swap{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_memory_swap{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_memory_swap{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_memory_swap{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_memory_swap{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_memory_swap{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "实际内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "container_memory_rss{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_memory_rss{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_memory_rss{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_memory_rss{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_memory_rss{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_memory_rss{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_memory_rss{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_memory_rss{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_memory_rss{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_memory_rss{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "5 分钟内最大内存使用量变化率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"checkoutservice.+\"}[5m])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    },
    {
     "expr": "rate(container_memory_max_usage_bytes{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "被映射到虚拟内存的文件大小",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 153 },
   "targets": [
    {
     "expr": "container_memory_mapped_file{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_memory_mapped_file{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_memory_mapped_file{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_memory_mapped_file{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_memory_mapped_file{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_memory_mapped_file{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_memory_mapped_file{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_memory_mapped_file{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_memory_mapped_file{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_memory_mapped_file{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": " 5 分钟内平均内存分配失败次数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 162 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_failures_total{pod=~\"frontend.+\"}[5m]))",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(rate(container_memory_failures_total{pod=~\"paymentservice.+\"}[5m]))",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "sum(rate(container_memory_failures_total{pod=~\"recommendationservice.+\"}[5m]))",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "sum(rate(container_memory_failures_total{pod=~\"checkoutservice.+\"}[5m]))",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "sum(rate(container_memory_failures_total{pod=~\"emailservice.+\"}[5m]))",
     "legendFormat": "emailservice"
    },
    {
     "expr": "sum(rate(container_memory_failures_total{pod=~\"cartservice.+\"}[5m]))",
     "legendFormat": "cartservice"
    },
    {
     "expr": "sum(rate(container_memory_failures_total{pod=~\"currencyservice.+\"}[5m]))",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "sum(rate(container_memory_failures_total{pod=~\"productcatalogservice.+\"}[5m]))",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "sum(rate(container_memory_failures_total{pod=~\"redis.+\"}[5m]))",
     "legendFormat": "redis"
    },
    {
     "expr": "sum(rate(container_memory_failures_total{pod=~\"shippingservice.+\"}[5m]))",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": " 5 分钟内 内存使用次数达到限制 变化率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "rate(container_memory_failcnt{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_memory_failcnt{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_memory_failcnt{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_memory_failcnt{pod=~\"checkoutservice.+\"}[5m])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_memory_failcnt{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_memory_failcnt{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_memory_failcnt{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_memory_failcnt{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_memory_failcnt{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    },
    {
     "expr": "rate(container_memory_failcnt{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": " 5 分钟内平均缓存内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 180 },
   "targets": [
    {
     "expr": "rate(container_memory_cache{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_memory_cache{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_memory_cache{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_memory_cache{pod=~\"checkoutservice.+\"}[$__rate_interval])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_memory_cache{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_memory_cache{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_memory_cache{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_memory_cache{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_memory_cache{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    },
    {
     "expr": "rate(container_memory_cache{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "最后一次观察到的时间戳",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 189 },
   "targets": [
    {
     "expr": "container_last_seen{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_last_seen{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_last_seen{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_last_seen{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_last_seen{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_last_seen{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_last_seen{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_last_seen{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_last_seen{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_last_seen{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "文件描述符数量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 198 },
   "targets": [
    {
     "expr": "container_file_descriptors{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_file_descriptors{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_file_descriptors{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_file_descriptors{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_file_descriptors{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_file_descriptors{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_file_descriptors{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_file_descriptors{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_file_descriptors{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_file_descriptors{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  },
  {
   "title": "5 分钟内平均用户态 CPU 使用时间",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 207 },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=~\"currencyservice.+\"}[5m])",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=~\"recommendationservice.+\"}[5m])",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=~\"frontend.+\"}[5m])",
     "legendFormat": "frontend"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=~\"cartservice.+\"}[5m])",
     "legendFormat": "cartservice"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=~\"checkoutservice.+\"}[5m])",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=~\"emailservice.+\"}[5m])",
     "legendFormat": "emailservice"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=~\"paymentservice.+\"}[5m])",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=~\"productcatalogservice.+\"}[5m])",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=~\"shippingservice.+\"}[5m])",
     "legendFormat": "shippingservice"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=~\"redis.+\"}[5m])",
     "legendFormat": "redis"
    }
   ]
  },
  {
   "title": " 10 秒内 CPU 负载平均值",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 216 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{pod=~\"frontend.+\"}",
     "legendFormat": "frontend"
    },
    {
     "expr": "container_cpu_load_average_10s{pod=~\"paymentservice.+\"}",
     "legendFormat": "paymentservice"
    },
    {
     "expr": "container_cpu_load_average_10s{pod=~\"recommendationservice.+\"}",
     "legendFormat": "recommendationservice"
    },
    {
     "expr": "container_cpu_load_average_10s{pod=~\"checkoutservice.+\"}",
     "legendFormat": "checkoutservice"
    },
    {
     "expr": "container_cpu_load_average_10s{pod=~\"emailservice.+\"}",
     "legendFormat": "emailservice"
    },
    {
     "expr": "container_cpu_load_average_10s{pod=~\"cartservice.+\"}",
     "legendFormat": "cartservice"
    },
    {
     "expr": "container_cpu_load_average_10s{pod=~\"currencyservice.+\"}",
     "legendFormat": "currencyservice"
    },
    {
     "expr": "container_cpu_load_average_10s{pod=~\"productcatalogservice.+\"}",
     "legendFormat": "productcatalogservice"
    },
    {
     "expr": "container_cpu_load_average_10s{pod=~\"redis.+\"}",
     "legendFormat": "redis"
    },
    {
     "expr": "container_cpu_load_average_10s{pod=~\"shippingservice.+\"}",
     "legendFormat": "shippingservice"
    }
   ]
  }
 ]
}