# Generated by Django 4.1.7 on 2024-06-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('algorithm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(max_length=255, null=True)),
                ('dataset_path', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('start_time', models.CharField(max_length=255, null=True)),
                ('end_time', models.CharField(max_length=255, null=True)),
                ('pid', models.CharField(max_length=255, null=True)),
                ('create_person', models.CharField(max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_name', models.CharField(max_length=100, null=True)),
                ('algorithms', models.CharField(max_length=100, null=True)),
                ('evaluation_metrics', models.CharField(max_length=100, null=True)),
                ('create_person', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(null=True)),
                ('algorithm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm_app.algorithmtype')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboard_app.leaderboarddataset')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardOverall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gold', models.IntegerField(null=True)),
                ('silver', models.IntegerField(null=True)),
                ('copper', models.IntegerField(null=True)),
                ('strawberry', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm_app.algorithm')),
                ('algorithm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm_app.algorithmtype')),
                ('evaluation_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm_app.evaluationindicator')),
            ],
        ),
    ]
